### ISSUE TITLE
Possibly bug. Android 4.0.3

### ISSUE THREAD

**Issue by snipervld** [Julien-Mialon/StormXamarin#1]
Storm.Mvvm 1.2.10
Storm.Mvvm.Android 1.2.16
.NET 4.5

I'm trying build android application using this lib, but this bug appears at build process.

Output:
Xamarin.Android.Common.targets(1307,5): error MSB4018: Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'System.Void Android.Views.View::SetPaddingRelative(System.Int32,System.Int32,System.Int32,System.Int32)' (defined in 'Storm.Mvvm.Android, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null') from 'Storm.Mvvm.Android, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Views.View::SetPaddingRelative(System.Int32,System.Int32,System.Int32,System.Int32)

**Comment by snipervld** [comment]
I create a new project, write simple app, but there is another error: "System.Exception: AndroidContainer has not been created
at Storm.Mvvm.Inject.AndroidContainer.GetInstance () <IL 0x00011, 0x0007c>
at Storm.Mvvm.ActivityBase.OnStart () <IL 0x00006, 0x00067>
at Android.App.Activity.n_OnStart (intptr,intptr) [0x00009]"

**Comment by Julien-Mialon** [comment]
Hello, can you send me your project in order that I take a look to this error, I can't repro it.

**Comment by snipervld** [comment]
Strangely, but i cannot reproduce this bug too, because, maybe, i somehow change application (rewrote some code pieces) and this bug disappear, even on android 4.1 and lower. Now, everything works like a sharm. But yesterday this bug was present on android 4.1 and lower (Inattentively looked at an example)
Sorry, that reported on the non-bug

**Comment by snipervld** [comment]
I was able to reproduce this bug. This bug appears only on Release configuration
https://onedrive.live.com/redir?resid=BE878B196C95461B!1025&authkey=!AB5_-rQZTcC1SnU&ithint=file%2crar

**Comment by Julien-Mialon** [comment]
Hello,

I just checked your project, indeed there is an issue relative to linking xamarin assembly. But you can easily solve it by setting your compile sdk to last version.
Something relative to that was posted on Xamarin forum : http://forums.xamarin.com/discussion/24845/linkassemblies-task-failed-unexpectedly or mvvm cross issue tracker https://github.com/MvvmCross/MvvmCross/issues/629.
I admit that I don't really know where it come from but seems to work if you change the compile sdk. (If you set the min api level below compile sdk, you can still support older api without any problems).

Hope this workaround will work for you.
