### ISSUE TITLE
Button Click in Fragment

### ISSUE THREAD

**Issue by snipervld** [Julien-Mialon/StormXamarin#3]
Hello (again). I have another issue. When i click a button in fragment, button's attached ICommand execute twice.

https://onedrive.live.com/redir?resid=BE878B196C95461B!1057&authkey=!ADrXEDjtl4gcsvk&ithint=file%2crar

**Comment by snipervld** [comment]
AlertDialog shows twice (when you click OK, another AlertDialog appears)

**Comment by Julien-Mialon** [comment]
This is weird, I never encountered this before. I'm gonna look into it asap.

**Comment by Julien-Mialon** [comment]
Hello,

This is now fixed in version 1.2.20, caused by setting view models two times in fragment.
